cafe: different behavior
Now when /tmp/caffeinated exists the system will lock then DELETE the
file

diff --git a/bash/bin/cafe b/bash/bin/cafe
--- a/bash/bin/cafe
+++ b/bash/bin/cafe
@@ -1,2 +1,9 @@
-touch /tmp/caffeinated
-(sleep $@ && rm /tmp/caffeinated)&
+#!/bin/sh
+set -e
+
+if [ ! -f /tmp/caffeinated ]; then
+	touch /tmp/caffeinated
+else 
+	echo "Can't cafe, already caffeinated!"
+	exit 1
+fi
diff --git a/bash/bin/uncafe b/bash/bin/uncafe
--- a/bash/bin/uncafe
+++ b/bash/bin/uncafe
@@ -1,1 +1,9 @@
-rm /tmp/caffeinated 2> /dev/null
+#!/bin/sh
+set -e
+
+if [ -f /tmp/caffeinated ]; then
+	rm /tmp/caffeinated 2> /dev/null 
+else 
+	echo "Can't uncafe, not caffeinated!";
+	exit 1
+fi
